takanome-dev/blog-with-astro-golang

client/src/components/card.astro, client/src/layouts/dashboard-layout.astro, client/src/layouts/new-post-layout.astro, client/src/pages/dashboard/drafts.astro, client/src/pages/dashboard/index.astro, client/src/pages/post/new.astro
=> feat: mark posts as draft

client/src/layouts/dashboard-layout.astro, client/src/layouts/new-post-layout.astro, client/src/pages/dashboard/index.astro, client/src/pages/login.astro, client/src/pages/post/new.astro, client/src/pages/posts/[id].astro, package.json, pnpm-lock.yaml, server/internal/auth/middleware.go, server/main.go, server/pkg/controllers/auth.controller.go, server/pkg/controllers/posts.controller.go, server/pkg/routes/posts.route.go, server/pkg/utils/cookies.go
This PR introduces a new feature that replaces the usage of local storage with cookies. By using cookies, we ensure a more secure and efficient way of storing data. This change enhances the overall performance and reliability of the application.
_Generated using [OpenSauced](https://opensauced.ai/)._
Fixes #17
=> feat: use cookies instead of localstorage

.gitignore, README.md, server/Makefile
This PR adds a Makefile to the project, which will help automate common tasks and improve the development workflow. The Makefile includes commands for building, testing, and cleaning the project. This addition will make it easier for contributors to get started with the project and ensure consistent and reliable builds.
_Generated using [OpenSauced](https://opensauced.ai/)._
=> chore: add makefile

.github/workflows/codeql.yml, server/go.mod
This PR adds the codeql.yml file for code analysis. It is a chore task to set up the necessary configuration for CodeQL. This file will enable automated code scanning and help identify potential vulnerabilities and bugs in the codebase.
_Generated using [OpenSauced](https://opensauced.ai/)._
=> ci: create codeql.yml

server/main.go
=> refactor: update server addr and add health route

server/main.go, server/pkg/config/db.go
=> Log err loading env

client/src/components/header.astro, client/src/layouts/dashboard-layout.astro, client/src/layouts/new-post-layout.astro, package-lock.json
added the sticky class to the header working on #30
=> made header sticky

server/main.go, server/pkg/utils/cookies.go
=> fix: update allowed origins

client/astro.config.mjs, client/package.json, client/pnpm-lock.yaml
=> feat: add vercel adapter for ssr

client/src/components/action-menu.astro, client/src/layouts/dashboard-layout.astro, client/src/pages/dashboard/analytics.astro, client/src/pages/dashboard/drafts.astro, client/src/pages/dashboard/index.astro, client/src/pages/posts/[id].astro, client/src/pages/user/[username].astro, server/main.go
=> fix: allow unauthed users to view a post

client/src/pages/login.astro, client/src/pages/register.astro, server/main.go
=> fix: cors issues

LICENSE, server/.air.toml
This pr adds a license
Fixes #38
=> chore: add license

client/astro.config.mjs, client/src/components/action-menu.astro, client/src/components/card.astro, client/src/pages/dashboard/drafts.astro, client/src/pages/dashboard/index.astro, client/src/pages/index.astro, client/src/pages/post/edit/[id].astro, client/src/pages/posts/[id].astro, client/src/pages/posts/index.astro, client/src/types/post.ts, server/Makefile, server/internal/database/posts.sql.go, server/pkg/controllers/posts.controller.go, server/pkg/controllers/users.controller.go, server/pkg/routes/users.route.go, server/sql/queries/posts.sql, server/tmp/build-errors.log
This pr joins the posts data with the users table and remove hardcoded data in the dashboard. Fixes also a bug where authed users can delete posts that they don't own :bug: 
Fixes #26
=> feat: join posts with users and remove hardcoded data

client/src/layouts/dashboard-layout.astro, client/src/pages/index.astro, client/src/pages/posts/[id].astro, client/src/pages/posts/index.astro, client/src/types/comment.ts, server/internal/database/comments.sql.go, server/internal/database/models.go, server/internal/database/posts.sql.go, server/pkg/controllers/comments.controller.go, server/pkg/controllers/posts.controller.go, server/sql/queries/comments.sql, server/sql/queries/posts.sql, server/sql/schema/007_add_edited_to_comments.sql, server/tmp/build-errors.log
This PR adds the functionality to edit and delete a comment.
Fixes #68 
| | |
| ------ | ------ |
| ![2023-10-30_22-23](https://github.com/takanome-dev/blog-with-astro-golang/assets/79809121/6773392b-a023-4b7b-a585-4067bcfb4602) | ![2023-10-30_22-24](https://github.com/takanome-dev/blog-with-astro-golang/assets/79809121/c04f2204-b7d6-4df0-94c7-78d7303e4870) |
=> feat: add edit and delete comment

client/src/pages/dashboard/drafts.astro, client/src/pages/dashboard/index.astro, server/internal/database/posts.sql.go, server/pkg/controllers/posts.controller.go, server/pkg/routes/posts.route.go, server/sql/queries/posts.sql
This PR moves the logic of filtering draft posts to the server side.
Fixes #65
=> refactor: move filtering draft posts to backend

client/astro.config.mjs, client/pnpm-lock.yaml
=> feat: enable vercel analytics

server/pkg/utils/cookies.go
=> fix: set samesite to none

server/main.go
This pr allows all origins to make requests to the backend for now. I've been hitting an annoying Cors issue for so long now and decided to disable it so that people can log in and create posts.
=> fix: allow all origins for now

.gitignore, server/main.go
This PR adds allow headers to cors options
=> fix: allow all origins

client/.vercel/README.txt, client/.vercel/project.json, client/src/components/footer.astro, client/src/components/header.astro, client/src/functions/auth-check.js, client/src/pages/about.astro, client/src/pages/dashboard/analytics.astro, client/src/pages/dashboard/drafts.astro, client/src/pages/dashboard/index.astro, client/src/pages/index.astro, client/src/pages/login.astro, client/src/pages/post/edit/[id].astro, client/src/pages/post/new.astro, client/src/pages/register.astro, client/src/pages/signout.astro, client/src/pages/user/[username].astro, server/pkg/utils/.null-ls_621893_cookies.go, server/pkg/utils/cookies.go
=> refactor: cleanup overal site

client/.gitignore, client/src/layouts/base-layout.astro, client/src/layouts/layout.astro, client/src/pages/dashboard/analytics.astro, client/src/pages/dashboard/index.astro, client/src/pages/index.astro, client/src/pages/user/[username].astro, server/main.go, server/tmp/build-errors.log
This pr corrects the site titles to include the name and remove duplicates.
Fixes #72
=> refactor: correct site titles
